# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/976487b1-fd54-4b35-844c-e655e3ddf9e9";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/33CC-280B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Secondary SSD
  fileSystems."/datastore" = {
    device = "/dev/disk/by-uuid/8049d944-3cc9-440f-928c-6e669a5775c2";
    fsType = "ext4";
    options = ["defaults"];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/de62a567-2963-43e7-9be9-2e9d8332a57c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
